import { PENALTY_LABELS } from "../domain/constants";
import { removePeriod } from "../domain/inputMutations";
import type { CourseConflict, SoftWeights, TimetableInput } from "../domain/types";
import { HelpText, SlotPicker } from "./FormControls";

export function RulesEditor({ input, onChange }: { input: TimetableInput; onChange: (next: TimetableInput) => void }) {
  return <section className="editor-panel" aria-labelledby="rules-title">
    <header className="section-title"><div><span>مرحله ۳</span><h2 id="rules-title">تقویم، تعارض‌ها و وزن‌ها</h2></div><p>در این مرحله قواعد سراسری نیمسال را تعریف می‌کنید. هر بازه‌ای که دستی اضافه می‌شود، از همان ردیف قابل حذف است.</p></header>
    <aside className="step-guide"><strong>قاعدهٔ ساده برای انتخاب نوع محدودیت</strong><div className="rule-comparison"><span><b>ممنوع / سخت</b> اگر نقض آن برنامه را واقعاً غیرقابل اجرا می‌کند.</span><span><b>نامطلوب / نرم</b> اگر رعایت آن بهتر است، ولی در شرایط دشوار قابل چشم‌پوشی است.</span></div><p><b>مثال تعطیلی:</b> برای تعطیلی کامل یک روز، روز را غیرفعال کنید. برای تعطیلی چند ساعت، خانه‌های همان روز و بازه را در جدول تعطیلی انتخاب کنید.</p></aside>

    <div className="settings-grid">
      <section className="settings-box"><h3>روزهای آموزشی فعال</h3><p className="help-text">روز غیرفعال در هیچ برنامه‌ای استفاده نمی‌شود. محدودیت یک استاد یا یک جلسه را از بخش خودش ثبت کنید.</p><div className="day-toggle-grid">{input.days.map((day) => <label className={day.enabled ? "day-toggle active" : "day-toggle"} key={day.id}><input type="checkbox" checked={day.enabled} onChange={(event) => onChange({ ...input, days: input.days.map((item) => item.id === day.id ? { ...item, enabled: event.target.checked } : item) })} /><span>{day.label}</span><small>{day.enabled ? "فعال" : "تعطیل"}</small></label>)}</div></section>

      <section className="settings-box periods-box"><div className="box-heading"><div><h3>بازه‌ها و وقفه‌ها</h3><small>الگوی زمانی برای همهٔ روزهای فعال یکسان است.</small></div><button type="button" onClick={() => { const index = input.periods.length; const last = input.periods[input.periods.length - 1]; onChange({ ...input, periods: [...input.periods, { index, label: `بازه ${index + 1}`, start: last?.end ?? "08:00", end: "20:45", breakAfter: false }] }); }}>افزودن بازه</button></div>
        <div className="period-list">{input.periods.map((period) => <article className="period-row" key={period.index}><div className="period-number">{(period.index + 1).toLocaleString("fa-IR")}</div><label>عنوان<input value={period.label} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, label: event.target.value } : item) })} /><HelpText>مثال: «بازه ۱» یا «صبح اول».</HelpText></label><label>شروع<input dir="ltr" type="time" value={period.start} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, start: event.target.value } : item) })} /></label><label>پایان<input dir="ltr" type="time" value={period.end} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, end: event.target.value } : item) })} /></label><label className="inline-check"><input type="checkbox" checked={period.breakAfter} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, breakAfter: event.target.checked, breakLabel: event.target.checked ? (item.breakLabel || "وقفه") : undefined } : item) })} />وقفه بعد از این بازه</label>{period.breakAfter && <label>عنوان وقفه<input value={period.breakLabel ?? "وقفه"} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, breakLabel: event.target.value } : item) })} /></label>}<button type="button" className="danger-button" disabled={input.periods.length <= 1} title={input.periods.length <= 1 ? "حداقل یک بازه باید باقی بماند." : undefined} onClick={() => { if (!window.confirm(`بازهٔ «${period.label}» حذف شود؟\n\nزمان ثابت روی این بازه پاک می‌شود و شمارهٔ بازه‌های بعدی یک واحد کاهش می‌یابد. قواعد زمانی نیز به‌صورت خودکار بازشماری می‌شوند.`)) return; onChange(removePeriod(input, period.index)); }}>حذف این بازه</button></article>)}</div>
      </section>
    </div>

    <section className="settings-box closed-slots-box"><div className="box-heading"><div><h3>تعطیلی دانشگاه و بسته‌بودن سراسری</h3><small>این انتخاب برای همهٔ استادان، گروه‌ها، درس‌ها و اتاق‌ها قید سخت است.</small></div><button type="button" disabled={!input.closedSlots.length} onClick={() => onChange({ ...input, closedSlots: [] })}>پاک‌کردن همه</button></div><SlotPicker input={input} value={input.closedSlots} onChange={(closedSlots) => onChange({ ...input, closedSlots })} ariaLabel="بازه‌های تعطیل سراسری" emptyText="تعطیلی سراسری ثبت نشده است." /></section>

    <section className="settings-box"><div className="box-heading"><div><h3>تعارض گروه‌های درسی</h3><small>برای دو درس مستقل که نباید یا بهتر است هم‌زمان نشوند.</small></div><button type="button" disabled={input.courses.length < 2} onClick={() => onChange({ ...input, conflicts: [...input.conflicts, { id: `conflict-${crypto.randomUUID()}`, firstCourseId: input.courses[0]?.id ?? "", secondCourseId: input.courses[1]?.id ?? "", kind: "soft", weight: 1 }] })}>افزودن تعارض</button></div>
      <div className="concept-note"><b>سخت:</b> هم‌زمانی کاملاً ممنوع است. <b>نرم:</b> هم‌زمانی ممکن است، اما به تابع جریمه اضافه می‌شود.</div>
      {input.conflicts.length ? input.conflicts.map((conflict) => <div className="conflict-row" key={conflict.id}><label>گروه درسی اول<select aria-label="گروه درسی اول" value={conflict.firstCourseId} onChange={(event) => updateConflict(input, onChange, conflict.id, { firstCourseId: event.target.value })}>{input.courses.map((course) => <option key={course.id} value={course.id}>{course.code} / گروه {course.groupNumber}</option>)}</select></label><span aria-hidden="true">با</span><label>گروه درسی دوم<select aria-label="گروه درسی دوم" value={conflict.secondCourseId} onChange={(event) => updateConflict(input, onChange, conflict.id, { secondCourseId: event.target.value })}>{input.courses.map((course) => <option key={course.id} value={course.id}>{course.code} / گروه {course.groupNumber}</option>)}</select></label><label>نوع تعارض<select aria-label="نوع تعارض" value={conflict.kind} onChange={(event) => updateConflict(input, onChange, conflict.id, { kind: event.target.value as CourseConflict["kind"] })}><option value="hard">سخت؛ هم‌زمانی ممنوع</option><option value="soft">نرم؛ هم‌زمانی جریمه‌دار</option></select></label><label>شدت تعارض نرم<input type="number" min="1" value={conflict.weight} disabled={conflict.kind === "hard"} onChange={(event) => updateConflict(input, onChange, conflict.id, { weight: Math.max(1, Math.round(Number(event.target.value))) })} /><HelpText>فقط برای تعارض نرم؛ مقدار بزرگ‌تر اهمیت بیشتر دارد.</HelpText></label><button className="danger-button" type="button" onClick={() => onChange({ ...input, conflicts: input.conflicts.filter((item) => item.id !== conflict.id) })}>حذف تعارض</button></div>) : <p className="empty-note">تعارض مستقلی ثبت نشده است. تداخل استاد، گروه دانشجویی و اتاق به‌صورت خودکار کنترل می‌شود.</p>}
    </section>

    <section className="settings-box"><h3>وزن‌های سراسری جریمه‌های نرم</h3><p className="help-text">وزن نشان می‌دهد حل‌کننده برای پرهیز از هر نوع مسئله چقدر تلاش کند. وزن دوبرابر تقریباً یعنی آن رخداد دو برابر مهم‌تر است. تغییر وزن‌ها را فقط وقتی انجام دهید که اولویت مدیریتی مشخصی دارید.</p><div className="weight-grid">{Object.entries(input.weights).map(([key, value]) => <label key={key}>{PENALTY_LABELS[key as keyof SoftWeights]}<input type="number" min="0" value={value} disabled={key === "unscheduledSession"} aria-describedby={key === "unscheduledSession" ? "unscheduled-weight-note" : undefined} onChange={(event) => onChange({ ...input, weights: { ...input.weights, [key]: Math.max(0, Math.round(Number(event.target.value))) } })} /><HelpText>{weightHelp(key as keyof SoftWeights)}</HelpText></label>)}</div><p id="unscheduled-weight-note" className="help-text">جریمهٔ جلسهٔ تخصیص‌نیافته ثابت و بسیار بزرگ است؛ موتور ابتدا تعداد جلسه‌های قابل زمان‌بندی را حفظ می‌کند و سپس ترجیحات نرم را بهبود می‌دهد.</p></section>

    <section className="settings-box"><h3>سیاست حل</h3><div className="responsive-fields"><label>حد روش دقیق<input type="number" value={input.settings.exactCourseLimit} disabled /><HelpText>روش دقیق برای حداکثر ۴۰ گروه درسی فعال است.</HelpText></label><label>زمان حل دقیق (ثانیه)<input type="number" value={input.settings.exactTimeLimitSeconds} min="30" max="285" onChange={(event) => onChange({ ...input, settings: { ...input.settings, exactTimeLimitSeconds: Math.min(285, Math.max(30, Number(event.target.value))) } })} /><HelpText>پس از پایان زمان، پاسخ FEASIBLE ممکن است بدون اثبات بهینگی برگردد.</HelpText></label><label>تلاش روش سریع<input type="number" min="20" max="1000" value={input.settings.fastAttempts} onChange={(event) => onChange({ ...input, settings: { ...input.settings, fastAttempts: Math.min(1000, Math.max(20, Number(event.target.value))) } })} /><HelpText>تعداد بیشتر معمولاً کیفیت را بهتر و زمان مرورگر را طولانی‌تر می‌کند.</HelpText></label><label>حداقل فاصلهٔ مطلوب جلسات یک درس<input type="number" min="0" max={input.days.length} value={input.settings.minimumDayGap} onChange={(event) => onChange({ ...input, settings: { ...input.settings, minimumDayGap: Math.min(input.days.length, Math.max(0, Number(event.target.value))) } })} /><HelpText>قید نرم است؛ مثال: مقدار ۲ یعنی یک روز فاصله کافی نیست.</HelpText></label></div></section>
  </section>;
}

function updateConflict(input: TimetableInput, onChange: (next: TimetableInput) => void, id: string, patch: Partial<CourseConflict>) {
  onChange({ ...input, conflicts: input.conflicts.map((item) => item.id === id ? { ...item, ...patch } : item) });
}

function weightHelp(key: keyof SoftWeights): string {
  return ({
    unscheduledSession: "برای جلوگیری از حذف جلسه و غیرقابل تغییر.",
    instructorUndesiredTime: "زمانی که استاد نامطلوب علامت زده است.",
    groupUndesiredTime: "زمان نامطلوب گروه دانشجویی.",
    sessionUndesiredTime: "ترجیح زمانی مخصوص همان جلسه.",
    preferredRoomRank: "دورشدن از رتبهٔ اول اتاق‌های ترجیحی.",
    missingPreferredEquipment: "نبود تجهیز مفید ولی غیرالزامی.",
    dailyLoad: "عبور از سقف نرم بازه‌های روزانه.",
    consecutivePeriods: "عبور از حد کلاس‌های پشت‌سرهم.",
    resourceGaps: "بازه‌های خالی میان اولین و آخرین کلاس روز.",
    buildingTravel: "تغییر ساختمان با حداقل یک بازه فاصله.",
    sameCourseSameDay: "چند جلسهٔ یک درس در یک روز.",
    minimumDayGap: "کمبود فاصلهٔ مطلوب میان جلسات یک درس.",
    softConflict: "هم‌زمانی دو درس دارای تعارض نرم.",
  })[key];
}
