import { PENALTY_LABELS } from "../domain/constants";
import type { CourseConflict, SoftWeights, TimetableInput } from "../domain/types";

const split = (value: string) => [...new Set(value.split(/[،,|]/).map((item) => item.trim()).filter(Boolean))];
const join = (value: string[]) => value.join("، ");

export function RulesEditor({ input, onChange }: { input: TimetableInput; onChange: (next: TimetableInput) => void }) {
  return <section className="editor-panel" aria-labelledby="rules-title">
    <header className="section-title"><div><span>مرحله ۳</span><h2 id="rules-title">تقویم، تعارض‌ها و وزن‌ها</h2></div><p>همهٔ روزها از الگوی زمانی مشترک استفاده می‌کنند. وقفه جزو مدت جلسه محسوب نمی‌شود.</p></header>
    <div className="settings-grid">
      <div className="settings-box"><h3>روزهای آموزشی</h3>{input.days.map((day) => <label className="inline-check" key={day.id}><input type="checkbox" checked={day.enabled} onChange={(event) => onChange({ ...input, days: input.days.map((item) => item.id === day.id ? { ...item, enabled: event.target.checked } : item) })} /><span>{day.label}</span></label>)}</div>
      <div className="settings-box"><div className="box-heading"><h3>بازه‌ها و وقفه‌ها</h3><div><button type="button" onClick={() => { const index = input.periods.length; onChange({ ...input, periods: [...input.periods, { index, label: `بازه ${index + 1}`, start: "19:15", end: "20:45", breakAfter: false }] }); }}>افزودن بازه</button><button type="button" className="danger-button" disabled={input.periods.length <= 1} onClick={() => { const last = input.periods.length - 1; if (!window.confirm("آخرین بازه حذف شود؟ زمان‌های ثابت یا قواعد وابسته را بازبینی کنید.")) return; onChange({ ...input, periods: input.periods.slice(0, -1), closedSlots: input.closedSlots.filter((slot) => Number(slot.split(":")[1]) !== last) }); }}>حذف بازه آخر</button></div></div>{input.periods.map((period) => <div className="period-row" key={period.index}><label>عنوان<input value={period.label} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, label: event.target.value } : item) })} /></label><label>شروع<input dir="ltr" type="time" value={period.start} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, start: event.target.value } : item) })} /></label><label>پایان<input dir="ltr" type="time" value={period.end} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, end: event.target.value } : item) })} /></label><label className="inline-check"><input type="checkbox" checked={period.breakAfter} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, breakAfter: event.target.checked, breakLabel: event.target.checked ? (item.breakLabel || "وقفه") : undefined } : item) })} />وقفه بعد از بازه</label>{period.breakAfter && <label>عنوان وقفه<input value={period.breakLabel ?? "وقفه"} onChange={(event) => onChange({ ...input, periods: input.periods.map((item) => item.index === period.index ? { ...item, breakLabel: event.target.value } : item) })} /></label>}</div>)}<label>تعطیلی دانشگاه (بازه‌های سخت)<input dir="ltr" placeholder="sat:0، sun:2" value={join(input.closedSlots)} onChange={(event) => onChange({ ...input, closedSlots: split(event.target.value) as TimetableInput["closedSlots"] })} /></label></div>
    </div>
    <div className="settings-box"><div className="box-heading"><h3>تعارض گروه‌های درسی</h3><button type="button" disabled={input.courses.length < 2} onClick={() => onChange({ ...input, conflicts: [...input.conflicts, { id: `conflict-${crypto.randomUUID()}`, firstCourseId: input.courses[0]?.id ?? "", secondCourseId: input.courses[1]?.id ?? "", kind: "soft", weight: 1 }] })}>افزودن تعارض</button></div>
      {input.conflicts.map((conflict) => <div className="conflict-row" key={conflict.id}><select aria-label="گروه درسی اول" value={conflict.firstCourseId} onChange={(event) => updateConflict(input, onChange, conflict.id, { firstCourseId: event.target.value })}>{input.courses.map((course) => <option key={course.id} value={course.id}>{course.code} / گروه {course.groupNumber}</option>)}</select><span>با</span><select aria-label="گروه درسی دوم" value={conflict.secondCourseId} onChange={(event) => updateConflict(input, onChange, conflict.id, { secondCourseId: event.target.value })}>{input.courses.map((course) => <option key={course.id} value={course.id}>{course.code} / گروه {course.groupNumber}</option>)}</select><select aria-label="نوع تعارض" value={conflict.kind} onChange={(event) => updateConflict(input, onChange, conflict.id, { kind: event.target.value as CourseConflict["kind"] })}><option value="hard">سخت؛ هم‌زمانی ممنوع</option><option value="soft">نرم؛ هم‌زمانی جریمه‌دار</option></select><label>شدت نرم<input type="number" min="1" value={conflict.weight} disabled={conflict.kind === "hard"} onChange={(event) => updateConflict(input, onChange, conflict.id, { weight: Math.max(0, Math.round(Number(event.target.value))) })} /></label><button className="danger-button" type="button" onClick={() => onChange({ ...input, conflicts: input.conflicts.filter((item) => item.id !== conflict.id) })}>حذف</button></div>)}
    </div>
    <div className="settings-box"><h3>وزن‌های سراسری جریمه‌های نرم</h3><p className="help-text">مقادیر بزرگ‌تر یعنی آن ترجیح در تصمیم حل‌کننده مهم‌تر است. جریمهٔ جلسهٔ تخصیص‌نیافته عمداً بسیار بزرگ است.</p><div className="weight-grid">{Object.entries(input.weights).map(([key, value]) => <label key={key}>{PENALTY_LABELS[key as keyof SoftWeights]}<input type="number" min="0" value={value} disabled={key === "unscheduledSession"} aria-describedby={key === "unscheduledSession" ? "unscheduled-weight-note" : undefined} onChange={(event) => onChange({ ...input, weights: { ...input.weights, [key]: Math.max(0, Math.round(Number(event.target.value))) } })} /></label>)}</div><p id="unscheduled-weight-note" className="help-text">جریمهٔ جلسهٔ تخصیص‌نیافته ثابت نگه داشته می‌شود؛ موتور ابتدا جلسه‌های اجباری و سپس تعداد کل جلسه‌ها را حفظ می‌کند.</p></div>
    <div className="settings-box"><h3>سیاست حل</h3><div className="responsive-fields"><label>حد روش دقیق<input type="number" value={input.settings.exactCourseLimit} disabled /></label><label>زمان حل دقیق (ثانیه)<input type="number" value={input.settings.exactTimeLimitSeconds} min="30" max="285" onChange={(event) => onChange({ ...input, settings: { ...input.settings, exactTimeLimitSeconds: Math.min(285, Math.max(30, Number(event.target.value))) } })} /></label><label>تلاش روش سریع<input type="number" min="20" max="1000" value={input.settings.fastAttempts} onChange={(event) => onChange({ ...input, settings: { ...input.settings, fastAttempts: Number(event.target.value) } })} /></label><label>حداقل فاصله روز جلسات<input type="number" min="0" max={input.days.length} value={input.settings.minimumDayGap} onChange={(event) => onChange({ ...input, settings: { ...input.settings, minimumDayGap: Number(event.target.value) } })} /></label></div></div>
  </section>;
}

function updateConflict(input: TimetableInput, onChange: (next: TimetableInput) => void, id: string, patch: Partial<CourseConflict>) {
  onChange({ ...input, conflicts: input.conflicts.map((item) => item.id === id ? { ...item, ...patch } : item) });
}
